Ipelib: Canvas Class Reference
Canvas Class Reference
#import <ipecanvas_cocoa.h>
Inherits ipe::CanvasBase.
Instance Methods
() - Canvas
(virtual) - ~Canvas
(IpeCanvasView *) - view
(void) - button
(void) - mouseMove
(void) - key
(void) - scrollWheel
(void) - drawRect
Instance Methods inherited from ipe::CanvasBase
virtual ~CanvasBase ()
void setPage (const Page *page, int pno, int view, const Cascade *sheet)
void setResources (const PdfResources *resources)
Vector pan () const
double zoom () const
const Cascade * cascade () const
Vector center () const
Vector pos () const
Vector unsnappedPos () const
Vector globalPos () const
Vector simpleSnapPos () const
const Snap & snap () const
int additionalModifiers () const
void setAdditionalModifiers (int mod)
Vector devToUser (const Vector &arg) const
Vector userToDev (const Vector &arg) const
void setCanvasStyle (const Style &style)
Style canvasStyle () const
void setPan (const Vector &v)
void setZoom (double zoom)
void setSnap (const Snap &s)
void setDimmed (bool dimmed)
void setAutoOrigin (const Vector &v)
Matrix canvasTfm () const
void setObserver (CanvasObserver *observer)
void setFifiVisible (bool visible)
void setSelectionVisible (bool visible)
void setTool (Tool *tool)
void finishTool ()
Tool * tool ()
void update ()
void updateTool ()
int canvasWidth () const
int canvasHeight () const
Additional Inherited Members
Public Types inherited from ipe::CanvasBase
enum TModifiers { EShift = 0x100, EControl = 0x200, EAlt = 0x400, EMeta = 0x800 }
enum TCursor { EStandardCursor, EHandCursor, ECrossCursor, EDotCursor }
Class Methods inherited from ipe::CanvasBase
static int selectPageOrView (Document *doc, int page=-1, int startIndex=0, int pageWidth=240, int width=600, int height=480)
Protected Member Functions inherited from ipe::CanvasBase
CanvasBase ()
void drawPaper (cairo_t *cc)
void drawFrame (cairo_t *cc)
void drawAxes (cairo_t *cc)
void drawGrid (cairo_t *cc)
void drawObjects (cairo_t *cc)
void drawTool (Painter &painter)
void snapToPaperAndFrame ()
void refreshSurface ()
void computeFifi (double x, double y)
void drawFifi (cairo_t *cr)
Protected Attributes inherited from ipe::CanvasBase
CanvasObserver * iObserver
Tool * iTool
const Page * iPage
int iPageNumber
int iView
const Cascade * iCascade
Style iStyle
Vector iPan
double iZoom
Snap iSnap
bool iDimmed
bool iAutoSnap
Vector iAutoOrigin
int iAdditionalModifiers
bool iRepaintObjects
int iWidth
int iHeight
cairo_surface_t * iSurface
Vector iUnsnappedMousePos
Vector iMousePos
Vector iGlobalPos
Vector iOldFifi
bool iFifiVisible
Snap::TSnapModes iFifiMode
bool iSelectionVisible
Fonts * iFonts
Constructor & Destructor Documentation
- Canvas (IpeCanvasView *) view
References ipe::CanvasBase::iView.
- (virtual ~)Canvas
Method Documentation
- (IpeCanvasView*) view
- (void) button (bool) press (NSEvent *) event
- (void) mouseMove (NSEvent *) event
References ipe::CanvasObserver::canvasObserverPositionChanged(), ipe::CanvasBase::computeFifi(), ipe::CanvasBase::iHeight, ipe::CanvasBase::iObserver, ipe::CanvasBase::iTool, ipe::CanvasBase::iView, ipe::Tool::mouseMove(), and mouseMove.
Referenced by mouseMove.
- (void) key (NSEvent *) event
References ipe::CanvasBase::iTool, ipe::Tool::key(), and key.
Referenced by key.
- (void) scrollWheel (NSEvent *) event
References ipe::CanvasObserver::canvasObserverWheelMoved(), and ipe::CanvasBase::iObserver.
- (void) drawRect (NSRect) rect
References ipe::CanvasBase::canvasTfm(), ipe::Canvas::drawFifi(), ipe::CanvasBase::drawTool(), ipe::CanvasBase::iCascade, ipe::CanvasBase::iFifiVisible, ipe::CanvasBase::iFonts, ipe::CanvasBase::iHeight, ipe::CanvasBase::iPage, ipe::CanvasBase::iView, ipe::CanvasBase::iWidth, ipe::CanvasBase::iZoom, ipe::Painter::popMatrix(), ipe::Painter::pushMatrix(), and ipe::Painter::transform().
The documentation for this class was generated from the following files:
ipecanvas_cocoa.h
ipecanvas_cocoa.cpp