Ipelib: ipe::Thumbnail Class Reference
ipe::Thumbnail Class Reference
#include <ipethumbs.h>
Public Types
enum TargetFormat { ESVG, EPNG, EPS, EPDF }
Public Member Functions
Thumbnail (const Document *doc, int width)
~Thumbnail ()
int height () const
Buffer render (const Page *page, int view)
void saveRender (TargetFormat fm, const char *dst, const Page *page, int view, double zoom, bool transparent, bool nocrop)
Static Public Member Functions
static void savePNG (cairo_surface_t *surface, const char *dst)
Member Enumeration Documentation
enum ipe::Thumbnail::TargetFormat
Enumerator
ESVG
EPNG
EPS
EPDF
Constructor & Destructor Documentation
Thumbnail::Thumbnail (const Document * doc, int width)
References ipe::Document::cascade(), ipe::Cascade::findLayout(), ipe::Document::fontPool(), ipe::Rect::height(), ipe::Fonts::New(), ipe::Layout::paper(), and ipe::Rect::width().
Thumbnail::~Thumbnail ()
Member Function Documentation
int ipe::Thumbnail::height () const inline
Referenced by ipe::PageSelector::PageSelector().
Buffer Thumbnail::render (const Page * page, int view)
References ipe::Document::cascade(), ipe::Page::count(), ipe::Buffer::data(), ipe::Object::draw(), ipe::Layout::iOrigin, ipe::Page::object(), ipe::Page::objectVisible(), ipe::Layout::paper(), ipe::Painter::pushMatrix(), ipe::Rect::topLeft(), ipe::Vector::x, and ipe::Vector::y.
Referenced by ipe::PageSelector::PageSelector().
void Thumbnail::saveRender (TargetFormat fm, const char * dst, const Page * page, int view, double zoom, bool transparent, bool nocrop)
References ipe::Attribute::BACKGROUND(), ipe::Document::cascade(), ipe::Page::count(), ipe::Buffer::data(), ipe::Object::draw(), EPDF, EPNG, EPS, ESVG, ipe::Page::findLayer(), ipe::Cascade::findSymbol(), ipe::Rect::height(), ipe::Page::object(), ipe::Page::objectVisible(), ipe::Page::pageBBox(), ipe::Layout::paper(), ipe::Painter::pushMatrix(), savePNG(), ipe::Rect::topLeft(), ipe::Rect::width(), ipe::Vector::x, and ipe::Vector::y.
void Thumbnail::savePNG (cairo_surface_t * surface, const char * dst) static
Referenced by saveRender().
The documentation for this class was generated from the following files:
ipethumbs.h
ipethumbs.cpp