Ipelib: ipe::Face Class Reference
ipe::Face Class Reference
Ipe Cairo interface
#include <ipefonts.h>
Public Member Functions
Face (int id, const PdfResources *resources) noexcept
~Face () noexcept
bool matches (int id) const noexcept
FontType type () const noexcept
int width (int ch) const noexcept
int glyphIndex (int ch) noexcept
cairo_font_face_t * cairoFont () noexcept
Detailed Description
A typeface (aka font), actually loaded (from a font file or PDF file).
Constructor & Destructor Documentation
Face::Face (int id, const PdfResources * resources) noexcept
References ipe::PdfObj::array(), ipe::CIDType0, ipe::CIDType2, ipe::Buffer::data(), ipe::PdfObj::dict(), ipe::PdfDict::get(), ipe::PdfObj::name(), ipe::PdfArray::obj(), ipe::PdfObj::ref(), ipe::Buffer::size(), ipe::Truetype, ipe::Type1, ipe::Unsupported, ipe::PdfName::value(), ipe::PdfRef::value(), and ipe::String::z().
Face::~Face () noexcept
Member Function Documentation
bool ipe::Face::matches (int id) const inline noexcept
FontType ipe::Face::type () const inline noexcept
int Face::width (int ch) const noexcept
int Face::glyphIndex (int ch) noexcept
References ipe::CIDType0, ipe::CIDType2, ipe::Truetype, and ipe::Type1.
cairo_font_face_t* ipe::Face::cairoFont () inline noexcept
The documentation for this class was generated from the following files:
ipefonts.h
ipefonts.cpp