Ipelib: ipe::PsWriter Class Reference
ipe::PsWriter Class Reference
#include <ipepswriter.h>
Public Member Functions
PsWriter (TellStream &stream, const Document *doc, bool noColor)
~PsWriter ()
bool createHeader (int pno=0, int vno=0)
void createPageView (int pno=0, int vno=0)
void createXml (int compressLevel)
void createTrailer ()
Detailed Description
Create Postscript file.
This class is responsible for the creation of a Postscript file from the data. You have to create an PsWriter first, providing a stream that has been opened for (binary) writing and is empty.
Constructor & Destructor Documentation
PsWriter::PsWriter (TellStream & stream, const Document * doc, bool noColor)
Create Postscript writer operating on this (open and empty) file.
PsWriter::~PsWriter ()
Destructor.
Member Function Documentation
bool PsWriter::createHeader (int pno = 0, int view = 0)
Create the document header and prolog (the resources).
Embeds no fonts if pool is 0. Returns false if a TrueType font is present.
References ipe::Cascade::allNames(), ipe::Rect::bottomLeft(), ipe::Document::cascade(), ipe::String::empty(), ipe::ETiling, ipe::Font::ETrueType, ipe::Page::findLayer(), ipe::Cascade::findTiling(), ipe::Document::fontPool(), ipe::Tiling::iAngle, ipe::Document::SProperties::iAuthor, ipe::Document::SProperties::iCreator, ipe::Document::SProperties::iModified, ipe::IPELIB_VERSION, ipe::Tiling::iStep, ipe::Document::SProperties::iTitle, ipe::Tiling::iWidth, ipe::Document::page(), ipe::Document::properties(), ipe::String::size(), ipe::Rect::topRight(), ipe::Vector::x, and ipe::Vector::y.
Referenced by ipe::Document::exportView(), and ipe::Document::save().
void PsWriter::createPageView (int pno = 0, int vno = 0)
Create contents and page stream for this view.
Background is not shown.
References ipe::Document::cascade(), ipe::Page::count(), ipe::Object::draw(), ipe::Page::object(), ipe::Page::objectVisible(), and ipe::Document::page().
Referenced by ipe::Document::exportView(), and ipe::Document::save().
void PsWriter::createXml (int compressLevel)
Save information in XML format.
References ipe::DeflateStream::close(), and ipe::Document::saveAsXml().
Referenced by ipe::Document::save().
void PsWriter::createTrailer ()
Create the trailer of the Postscript file.
Referenced by ipe::Document::exportView(), and ipe::Document::save().
The documentation for this class was generated from the following files:
ipepswriter.h
ipepswriter.cpp