Ipelib: ipe::Fixed Class Reference
ipe::Fixed Class Reference
Ipe Base
#include <ipebase.h>
Public Member Functions
Fixed (int val)
Fixed ()
int toInt () const
double toDouble () const
int internal () const
Fixed mult (int a, int b) const
bool operator== (const Fixed &rhs) const
bool operator!= (const Fixed &rhs) const
bool operator< (const Fixed &rhs) const
Static Public Member Functions
static Fixed fromInternal (int32_t val)
static Fixed fromDouble (double val)
Friends
Stream & operator<< (Stream &stream, const Fixed &f)
Related Functions
(Note that these are not member functions.)
Stream & operator<< (Stream &stream, const Fixed &f)
Detailed Description
Fixed point number with three (decimal) fractional digits.
Constructor & Destructor Documentation
ipe::Fixed::Fixed (int val) inline explicit
ipe::Fixed::Fixed () inline explicit
Member Function Documentation
Fixed ipe::Fixed::fromInternal (int32_t val) inline static
Referenced by ipe::Color::Color(), ipe::Attribute::color(), fromDouble(), ipe::Lex::getFixed(), ipe::Attribute::number(), and ipe::String::unicode().
Fixed Fixed::fromDouble (double val) static
References fromInternal().
Referenced by ipe::Text::getAttribute().
int ipe::Fixed::toInt () const inline
double ipe::Fixed::toDouble () const inline
Referenced by ipe::Latex::createLatexSource(), ipe::CairoPainter::doDrawPath(), ipe::BBoxPainter::doDrawPath(), ipe::CairoPainter::doDrawText(), ipe::Reference::draw(), ipe::Path::drawArrow(), ipe::QIpe(), and ipe::Text::setAttribute().
int ipe::Fixed::internal () const inline
Referenced by ipe::Attribute::Attribute(), ipe::PdfPainter::drawAttributes(), and ipe::Canvas::sizeHint().
Fixed Fixed::mult (int a, int b) const
Return value times (a/b)
Referenced by ipe::Latex::createLatexSource(), and ipe::String::unicode().
bool ipe::Fixed::operator== (const Fixed & rhs) const inline
bool ipe::Fixed::operator!= (const Fixed & rhs) const inline
bool ipe::Fixed::operator< (const Fixed & rhs) const inline
Friends And Related Function Documentation
Stream& operator<< (Stream & stream, const Fixed & f) friend
Stream & operator<< (Stream & stream, const Fixed & f) related
References ipe::Lex::Lex().
The documentation for this class was generated from the following files:
ipebase.h
ipebase.cpp