Ipelib: ipe Namespace Reference
ipe Namespace Reference
Classes
class A85Source
class A85Stream
class AllAttributes
class Angle
class Arc
class Attribute
class Base64Source
class Base64Stream
class BBoxPainter
class Bezier
class Bitmap
class BitmapFinder
class Buffer
class BufferSource
class CairoPainter
class Canvas
class CanvasBase
class CanvasObserver
class Cascade
class ClosedSpline
class Color
class Curve
class CurveSegment
class DataSource
class DeflateStream
class Document
class Effect
class Ellipse
class Face
class FileSource
class FileStream
class Fixed
struct Font
class Fonts
struct Gradient
class Group
class Image
class ImlParser
class InflateSource
class Ipelet
struct IpeletData
class IpeletHelper
class Latex
struct Layout
class Lex
class Line
class Linear
class Matrix
class Object
class ObjectFactory
class Page
class PageSelector
class Painter
class PanTool
class Path
class PdfArray
class PdfBool
class PdfDict
class PdfFile
class PdfName
class PdfNull
class PdfNumber
class PdfObj
class PdfPainter
class PdfParser
class PdfRef
class PdfString
struct PdfToken
class PdfWriter
class Platform
class PsPainter
class PsWriter
class Rect
class Reference
class Repository
class Segment
class SelectTool
class Shape
class Snap
class Stream
class String
class StringStream
class StyleSheet
class SubPath
class Symbol
class TellStream
class Text
struct TextPadding
class Thumbnail
struct Tiling
class Tool
class TransformTool
class Vector
class Visitor
class XmlAttributes
class XmlParser
Typedefs
typedef std::vector< Attribute > AttributeSeq
Enumerations
enum Kind {
EPen = 0, ESymbolSize, EArrowSize, EColor,
EDashStyle, ETextSize, ETextStretch, ETextStyle,
EGridSize, EAngleSize, EOpacity, ETiling,
ESymbol, EGradient, EEffect
}
enum Property {
EPropPen = 0, EPropSymbolSize, EPropFArrow, EPropRArrow,
EPropFArrowSize, EPropRArrowSize, EPropFArrowShape, EPropRArrowShape,
EPropStrokeColor, EPropFillColor, EPropMarkShape, EPropPathMode,
EPropDashStyle, EPropTextSize, EPropTextStyle, EPropOpacity,
EPropTiling, EPropGradient, EPropHorizontalAlignment, EPropVerticalAlignment,
EPropLineJoin, EPropLineCap, EPropFillRule, EPropPinned,
EPropTransformations, EPropTransformableText, EPropMinipage, EPropWidth
}
enum TPathMode { EStrokedOnly, EStrokedAndFilled, EFilledOnly }
enum THorizontalAlignment { EAlignLeft, EAlignRight, EAlignHCenter }
enum TVerticalAlignment { EAlignBottom, EAlignBaseline, EAlignTop, EAlignVCenter }
enum TLineJoin { EDefaultJoin, EMiterJoin, ERoundJoin, EBevelJoin }
enum TLineCap { EDefaultCap, EButtCap, ERoundCap, ESquareCap }
enum TFillRule { EDefaultRule, EWindRule, EEvenOddRule }
enum TPinned { ENoPin = 0x00, EHorizontalPin = 0x01, EVerticalPin = 0x02, EFixedPin = 0x03 }
enum TTransformations { ETransformationsTranslations, ETransformationsRigidMotions, ETransformationsAffine }
enum TSelect { ENotSelected = 0, EPrimarySelected, ESecondarySelected }
Functions
template<class T >
T max (const T &lhs, const T &rhs)
template<class T >
T min (const T &lhs, const T &rhs)
double abs (double val)
QPointF QPt (const Vector &v)
String IpeQ (const QString &str)
QString QIpe (const String &str)
QColor QIpe (Color color)
Color IpeQ (QColor color)
Variables
const char *const kind_names []
const char *const property_names []
const int IPELIB_VERSION = 70110
const int OLDEST_FILE_FORMAT = 70000
const int FILE_FORMAT = 70107
Function Documentation
QPointF ipe::QPt (const Vector & v) inline
References ipe::Vector::x, and ipe::Vector::y.
String ipe::IpeQ (const QString & str) inline
Referenced by ipe::Canvas::keyPressEvent().
QString ipe::QIpe (const String & str) inline
References ipe::String::z().
QColor ipe::QIpe (Color color) inline
References ipe::Color::iBlue, ipe::Color::iGreen, ipe::Color::iRed, and ipe::Fixed::toDouble().
Color ipe::IpeQ (QColor color) inline